spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=TTS_TH04395;encrypt=true;trustServerCertificate=true;
    username: sa
    password: 123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true